### PR TITLE
Fix both light and dark images from appearing in light mode on the docs site

### PR DESCRIPTION
**Pull request by josh-wong**
## Related issue

**If applicable, please provide a link to the issue related to this change.**

- [ ] **Related issue:**
- [x] **No related issue**

## Description

**Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.**

A recent change in Material for MkDocs requires selectors to be added to `extra.css` when custom schemes are being used. Without the selectors, both light and dark images are displayed (in this case, only when in light mode).

This PR fixes both light and dark images from being displayed in light mode. The fix includes the following:

- Uncomments the hidden light and dark images in `docs/README.md`.
- Removes the static image that was used as a temporary fix in `docs/README.md`.
- Adds selectors to the custom schemes in `extra.css`.

> **Note**
>
> The fix for this follows the guidance from the following discussion in the Material for MkDocs repository:
> 
> - https://github.com/squidfunk/mkdocs-material/discussions/5596#discussioncomment-6133721
>
> I fixed the same issue on my site as well in the following PR: https://github.com/josh-wong/josh-wong.github.io/pull/15

### Type of change

- [ ] Documentation (new or updated documentation)
- [x] Improvement (an improvement to the existing state)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Bug fix (nonbreaking change that fixes an issue)

## How has this been tested?

**Please describe the tests that you ran to verify your changes and provide instructions so that we can reproduce. Please also list any relevant details for your test configuration.**

- [x] Implemented the fix as mentioned in https://github.com/squidfunk/mkdocs-material/discussions/5596#discussioncomment-6133721 (with a bit of troubleshooting). Then, ran the site locally to confirm only one image appeared as expected in both light and dark modes.

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by JavierEscobarOrtiz** [comment]
Hello @josh-wong,

Thanks for opening this PR. Two comments:

- Could you please change the target branch to 0.9.x?

- I am trying to reproduce the fix, but I am getting the same behavior as mentioned in the discussion, even when clearing the cache and running `mkdocs build`.

How did you get it to work?

**Comment by JoaquinAmatRodrigo** [comment]
It works!
Thanks a lot @josh-wong!

**Review by JoaquinAmatRodrigo — APPROVED** [review]

**Comment by JavierEscobarOrtiz** [comment]
Thanks a lot @josh-wong, I think it was something with my environment. I tried a new one and it works.

**Comment by JavierEscobarOrtiz** [comment]
@josh-wong you can merge the PR 😄

**Pull request merged**
