### PR TITLE
Support for multiple metrics in model_selection

### PR DESCRIPTION
**Pull request by Pablo-Davila**
Add support for multiple metrics when backtesting.
 - If `metric` is an instance of `str` or `callable` behavior is the same as before
 - If `metric` is an instance of `list`, multiple metrics will be calculated. Only the first metric will be considered in order to select the best parameters.

### CODE REVIEW

**Comment by JoaquinAmatRodrigo** [comment]
Hi @Pablo-Davila 
Thanks a lot for your contribution. It seems a great feature to add to the library.  I will review and test your request as soon as possible.
Best

**Comment by Pablo-Davila** [comment]
I have rebased the changes

**Comment by JoaquinAmatRodrigo** [comment]
Hi @Pablo-Davila 
We had added your recommendation to the coming release 0.5. Since we were already working with other previous branches, the  merge was painful. If you agree, we add your code (with a small modification) and mention you in the docs:

`metric` can be a list in `backtesting_forecaster`, `grid_search_forecaster`, `random_search_forecaster`, `backtesting_forecaster_multiseries`. If `metric` is a `list`, multiple metrics will be calculated. (suggested by Pablo Dávila Herrero https://github.com/Pablo-Davila)

Let us know if you are okay with it.

Thanks!

**Comment by Pablo-Davila** [comment]
It looks great to me! 👍

**Pull request closed without merging**
