### PR TITLE
Update forecaster-parameters.md

### PR DESCRIPTION
**Pull request by syndct**
Added documentation for the weight_func parameter and also fixed the import for ForecasterAutoregDirect examples.

### CODE REVIEW

**Comment by syndct** [comment]
Hi @JoaquinAmatRodrigo, I was working through the skforecast quick start documentation and just found a few things I thought I could try assist with. This an incredible library and I'm excited to use this in the future. Hope this helps the project.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @syndct,

We really appreciate your contribution to skforecast!
In order to maintain code integrity, we typically do not accept direct pull requests against the master branch. This allows us to thoroughly evaluate and ensure that any proposed changes integrate seamlessly with the existing code.
Could you change the target branch for this pull request from 'master' to '0.10.x'? This will allow for a smoother review process.

**Comment by JoaquinAmatRodrigo** [comment]
@JavierEscobarOrtiz, since you are the main developer of this doc section Could you review it? Thanks!

**Comment by JavierEscobarOrtiz** [comment]
Hello @syndct 

Thank you very much for reviewing this section, we weren't aware of these errors 😄 

Please, don't delete this "danger" and then we will accept the PR

imagen

**Review by JavierEscobarOrtiz — APPROVED** [review]

**Comment by JavierEscobarOrtiz** [comment]
You can now merge the PR 😄

**Pull request merged**
