### PR TITLE
Repeating SARIMAX .summary() bug fix

### PR DESCRIPTION
**Pull request by tyg3rr**
https://github.com/JoaquinAmatRodrigo/skforecast/pull/635

### CODE REVIEW

**Comment by tyg3rr** [comment]
I'm not sure what's going on here! This is my first major PR. Did you want me to PR a branch other than master?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @tyg3rr,
Please, change the target branch to 0.12.x

**Comment by tyg3rr** [comment]
@JoaquinAmatRodrigo it's giving me the following error: `There are no new commits between base branch '0.12.x' and head branch 'master'`

**Comment by JoaquinAmatRodrigo** [comment]
I have no idea what is going wrong XD
Let me close the PR and let's try with a new one

**Comment by tyg3rr** [comment]
Here's what I see trying to merge with 0.12.x
image
---
Here's what I see trying to merge with master
image

It seems like my merge with master would also introduce all of the other changes in 0.12.x between the last merge and my merge with 0.12.x. I think those changes are causing the unit test failures?

**Pull request closed without merging**
