### PR TITLE
Example of the usage of GLM Link functions and XGBoost custom objective to avoid negative predictions

### PR DESCRIPTION
**Pull request by edgBR**
Hi guys,

The example of avoiding negative predictions is nice but transforming your target sometimes have unwanted consequences. See: https://www.youtube.com/watch?v=fdKy_FFzZF4 

When dealing with zero inflated data (some rainfall series in certain countries) or intermittent power production forecasting this might be a bit tricky sometimes. I have added an example of using GammaRegressor as well as XGBoost with gamma function. If needed I can also add poisson regression examples for count data but it think it would be nice to have this already in the FAQ!.

I can also add a zero inflated forecast with a hurdle model as well.

BR
E

### CODE REVIEW

**Comment by JoaquinAmatRodrigo** [comment]
Hello @edgBR,

Thank you very much for your valuable contribution. We appreciate it!

We will now proceed with the review process. Meanwhile, would you mind changing the target branch to 0.9.x? This adjustment will help us align the changes with our current goals and ensure a smooth integration.

Best regards,

**Comment by edgBR** [comment]
> Hello @edgBR,
> 
> Thank you very much for your valuable contribution. We appreciate it!
> 
> We will now proceed with the review process. Meanwhile, would you mind changing the target branch to 0.9.x? This adjustment will help us align the changes with our current goals and ensure a smooth integration.
> 
> Best regards,

Done ;)

**Comment by JoaquinAmatRodrigo** [comment]
Very interesting contribution @edgBR !

**Review by JoaquinAmatRodrigo — APPROVED** [review]

**Comment by edgBR** [comment]
> Very interesting use case @edgBR! Thanks a lot for your contribution! The PR is approved, feel free to complete it.

Hi @JoaquinAmatRodrigo for some reason I can not complete the PR, I only have the option of close with comment. (My experience with github is limited as in my company we use devops and previously gitlab).

Might be related with this:

image

**Comment by JavierEscobarOrtiz** [comment]
Merged! Thank you very much @edgBR 😄

**Comment by JavierEscobarOrtiz** [comment]
@edgBR 👏 

https://skforecast.org/latest/faq/non-negative-predictions

**Pull request merged**
